services:
    server.api:
        image: ${DOCKER_REGISTRY-}taskforge.api
        container_name: TaskForge.Api
        build:
            context: .
            dockerfile: TaskForge.Api/Dockerfile
        depends_on:
            - taskforge-db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=5000
            - ASPNETCORE_HTTPS_PORTS=5001
            - ASPNETCORE_Kestrel__Certificates__Default__Password=slr300hdg6m1239
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${USERPROFILE}\.aspnet\https:/https/
        #            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        ports:
            - 5000:5000
            - 5001:5001
    
    taskforge-db:
        image: postgres:latest
        container_name: TaskForge.Db
        environment:
            - POSTGRES_DB=taskforge
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./.containers/database:/var/lib/postgresql/data
        ports:
            - 5432:5432 